purchase_type: on_demand
subnet_id: subnet-306b4654
num_instances: 2
key_name: adam-heller
security_group_ids: sg-f760d58e
instance_type: c4.large
tag_name: literate-garbanzo-producers
vol_size: 8
role: worker
use_eips: true
