/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.drfloob.insight.pulse.schema.gh.y2015;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Root extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2069734851689878197L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Root\",\"namespace\":\"com.drfloob.insight.pulse.schema.gh.y2015\",\"fields\":[{\"name\":\"type\",\"type\":[\"string\",\"null\"]},{\"name\":\"public\",\"type\":[\"boolean\",\"null\"]},{\"name\":\"payload\",\"type\":[\"string\",\"null\"]},{\"name\":\"repo_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"repo_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"repo_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"actor_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"actor_login\",\"type\":[\"string\",\"null\"]},{\"name\":\"actor_gravatar_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"actor_avatar_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"actor_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"org_id\",\"type\":[\"long\",\"null\"]},{\"name\":\"org_login\",\"type\":[\"string\",\"null\"]},{\"name\":\"org_gravatar_id\",\"type\":[\"string\",\"null\"]},{\"name\":\"org_avatar_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"org_url\",\"type\":[\"string\",\"null\"]},{\"name\":\"created_at\",\"type\":[\"long\",\"null\"]},{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"other\",\"type\":[\"string\",\"null\"]},{\"name\":\"rnd\",\"type\":[\"double\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence type;
  @Deprecated public java.lang.Boolean public$;
  @Deprecated public java.lang.CharSequence payload;
  @Deprecated public java.lang.Long repo_id;
  @Deprecated public java.lang.CharSequence repo_name;
  @Deprecated public java.lang.CharSequence repo_url;
  @Deprecated public java.lang.Long actor_id;
  @Deprecated public java.lang.CharSequence actor_login;
  @Deprecated public java.lang.CharSequence actor_gravatar_id;
  @Deprecated public java.lang.CharSequence actor_avatar_url;
  @Deprecated public java.lang.CharSequence actor_url;
  @Deprecated public java.lang.Long org_id;
  @Deprecated public java.lang.CharSequence org_login;
  @Deprecated public java.lang.CharSequence org_gravatar_id;
  @Deprecated public java.lang.CharSequence org_avatar_url;
  @Deprecated public java.lang.CharSequence org_url;
  @Deprecated public java.lang.Long created_at;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence other;
  @Deprecated public java.lang.Double rnd;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Root() {}

  /**
   * All-args constructor.
   * @param type The new value for type
   * @param public$ The new value for public
   * @param payload The new value for payload
   * @param repo_id The new value for repo_id
   * @param repo_name The new value for repo_name
   * @param repo_url The new value for repo_url
   * @param actor_id The new value for actor_id
   * @param actor_login The new value for actor_login
   * @param actor_gravatar_id The new value for actor_gravatar_id
   * @param actor_avatar_url The new value for actor_avatar_url
   * @param actor_url The new value for actor_url
   * @param org_id The new value for org_id
   * @param org_login The new value for org_login
   * @param org_gravatar_id The new value for org_gravatar_id
   * @param org_avatar_url The new value for org_avatar_url
   * @param org_url The new value for org_url
   * @param created_at The new value for created_at
   * @param id The new value for id
   * @param other The new value for other
   * @param rnd The new value for rnd
   */
  public Root(java.lang.CharSequence type, java.lang.Boolean public$, java.lang.CharSequence payload, java.lang.Long repo_id, java.lang.CharSequence repo_name, java.lang.CharSequence repo_url, java.lang.Long actor_id, java.lang.CharSequence actor_login, java.lang.CharSequence actor_gravatar_id, java.lang.CharSequence actor_avatar_url, java.lang.CharSequence actor_url, java.lang.Long org_id, java.lang.CharSequence org_login, java.lang.CharSequence org_gravatar_id, java.lang.CharSequence org_avatar_url, java.lang.CharSequence org_url, java.lang.Long created_at, java.lang.CharSequence id, java.lang.CharSequence other, java.lang.Double rnd) {
    this.type = type;
    this.public$ = public$;
    this.payload = payload;
    this.repo_id = repo_id;
    this.repo_name = repo_name;
    this.repo_url = repo_url;
    this.actor_id = actor_id;
    this.actor_login = actor_login;
    this.actor_gravatar_id = actor_gravatar_id;
    this.actor_avatar_url = actor_avatar_url;
    this.actor_url = actor_url;
    this.org_id = org_id;
    this.org_login = org_login;
    this.org_gravatar_id = org_gravatar_id;
    this.org_avatar_url = org_avatar_url;
    this.org_url = org_url;
    this.created_at = created_at;
    this.id = id;
    this.other = other;
    this.rnd = rnd;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return public$;
    case 2: return payload;
    case 3: return repo_id;
    case 4: return repo_name;
    case 5: return repo_url;
    case 6: return actor_id;
    case 7: return actor_login;
    case 8: return actor_gravatar_id;
    case 9: return actor_avatar_url;
    case 10: return actor_url;
    case 11: return org_id;
    case 12: return org_login;
    case 13: return org_gravatar_id;
    case 14: return org_avatar_url;
    case 15: return org_url;
    case 16: return created_at;
    case 17: return id;
    case 18: return other;
    case 19: return rnd;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = (java.lang.CharSequence)value$; break;
    case 1: public$ = (java.lang.Boolean)value$; break;
    case 2: payload = (java.lang.CharSequence)value$; break;
    case 3: repo_id = (java.lang.Long)value$; break;
    case 4: repo_name = (java.lang.CharSequence)value$; break;
    case 5: repo_url = (java.lang.CharSequence)value$; break;
    case 6: actor_id = (java.lang.Long)value$; break;
    case 7: actor_login = (java.lang.CharSequence)value$; break;
    case 8: actor_gravatar_id = (java.lang.CharSequence)value$; break;
    case 9: actor_avatar_url = (java.lang.CharSequence)value$; break;
    case 10: actor_url = (java.lang.CharSequence)value$; break;
    case 11: org_id = (java.lang.Long)value$; break;
    case 12: org_login = (java.lang.CharSequence)value$; break;
    case 13: org_gravatar_id = (java.lang.CharSequence)value$; break;
    case 14: org_avatar_url = (java.lang.CharSequence)value$; break;
    case 15: org_url = (java.lang.CharSequence)value$; break;
    case 16: created_at = (java.lang.Long)value$; break;
    case 17: id = (java.lang.CharSequence)value$; break;
    case 18: other = (java.lang.CharSequence)value$; break;
    case 19: rnd = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'public$' field.
   * @return The value of the 'public$' field.
   */
  public java.lang.Boolean getPublic$() {
    return public$;
  }

  /**
   * Sets the value of the 'public$' field.
   * @param value the value to set.
   */
  public void setPublic$(java.lang.Boolean value) {
    this.public$ = value;
  }

  /**
   * Gets the value of the 'payload' field.
   * @return The value of the 'payload' field.
   */
  public java.lang.CharSequence getPayload() {
    return payload;
  }

  /**
   * Sets the value of the 'payload' field.
   * @param value the value to set.
   */
  public void setPayload(java.lang.CharSequence value) {
    this.payload = value;
  }

  /**
   * Gets the value of the 'repo_id' field.
   * @return The value of the 'repo_id' field.
   */
  public java.lang.Long getRepoId() {
    return repo_id;
  }

  /**
   * Sets the value of the 'repo_id' field.
   * @param value the value to set.
   */
  public void setRepoId(java.lang.Long value) {
    this.repo_id = value;
  }

  /**
   * Gets the value of the 'repo_name' field.
   * @return The value of the 'repo_name' field.
   */
  public java.lang.CharSequence getRepoName() {
    return repo_name;
  }

  /**
   * Sets the value of the 'repo_name' field.
   * @param value the value to set.
   */
  public void setRepoName(java.lang.CharSequence value) {
    this.repo_name = value;
  }

  /**
   * Gets the value of the 'repo_url' field.
   * @return The value of the 'repo_url' field.
   */
  public java.lang.CharSequence getRepoUrl() {
    return repo_url;
  }

  /**
   * Sets the value of the 'repo_url' field.
   * @param value the value to set.
   */
  public void setRepoUrl(java.lang.CharSequence value) {
    this.repo_url = value;
  }

  /**
   * Gets the value of the 'actor_id' field.
   * @return The value of the 'actor_id' field.
   */
  public java.lang.Long getActorId() {
    return actor_id;
  }

  /**
   * Sets the value of the 'actor_id' field.
   * @param value the value to set.
   */
  public void setActorId(java.lang.Long value) {
    this.actor_id = value;
  }

  /**
   * Gets the value of the 'actor_login' field.
   * @return The value of the 'actor_login' field.
   */
  public java.lang.CharSequence getActorLogin() {
    return actor_login;
  }

  /**
   * Sets the value of the 'actor_login' field.
   * @param value the value to set.
   */
  public void setActorLogin(java.lang.CharSequence value) {
    this.actor_login = value;
  }

  /**
   * Gets the value of the 'actor_gravatar_id' field.
   * @return The value of the 'actor_gravatar_id' field.
   */
  public java.lang.CharSequence getActorGravatarId() {
    return actor_gravatar_id;
  }

  /**
   * Sets the value of the 'actor_gravatar_id' field.
   * @param value the value to set.
   */
  public void setActorGravatarId(java.lang.CharSequence value) {
    this.actor_gravatar_id = value;
  }

  /**
   * Gets the value of the 'actor_avatar_url' field.
   * @return The value of the 'actor_avatar_url' field.
   */
  public java.lang.CharSequence getActorAvatarUrl() {
    return actor_avatar_url;
  }

  /**
   * Sets the value of the 'actor_avatar_url' field.
   * @param value the value to set.
   */
  public void setActorAvatarUrl(java.lang.CharSequence value) {
    this.actor_avatar_url = value;
  }

  /**
   * Gets the value of the 'actor_url' field.
   * @return The value of the 'actor_url' field.
   */
  public java.lang.CharSequence getActorUrl() {
    return actor_url;
  }

  /**
   * Sets the value of the 'actor_url' field.
   * @param value the value to set.
   */
  public void setActorUrl(java.lang.CharSequence value) {
    this.actor_url = value;
  }

  /**
   * Gets the value of the 'org_id' field.
   * @return The value of the 'org_id' field.
   */
  public java.lang.Long getOrgId() {
    return org_id;
  }

  /**
   * Sets the value of the 'org_id' field.
   * @param value the value to set.
   */
  public void setOrgId(java.lang.Long value) {
    this.org_id = value;
  }

  /**
   * Gets the value of the 'org_login' field.
   * @return The value of the 'org_login' field.
   */
  public java.lang.CharSequence getOrgLogin() {
    return org_login;
  }

  /**
   * Sets the value of the 'org_login' field.
   * @param value the value to set.
   */
  public void setOrgLogin(java.lang.CharSequence value) {
    this.org_login = value;
  }

  /**
   * Gets the value of the 'org_gravatar_id' field.
   * @return The value of the 'org_gravatar_id' field.
   */
  public java.lang.CharSequence getOrgGravatarId() {
    return org_gravatar_id;
  }

  /**
   * Sets the value of the 'org_gravatar_id' field.
   * @param value the value to set.
   */
  public void setOrgGravatarId(java.lang.CharSequence value) {
    this.org_gravatar_id = value;
  }

  /**
   * Gets the value of the 'org_avatar_url' field.
   * @return The value of the 'org_avatar_url' field.
   */
  public java.lang.CharSequence getOrgAvatarUrl() {
    return org_avatar_url;
  }

  /**
   * Sets the value of the 'org_avatar_url' field.
   * @param value the value to set.
   */
  public void setOrgAvatarUrl(java.lang.CharSequence value) {
    this.org_avatar_url = value;
  }

  /**
   * Gets the value of the 'org_url' field.
   * @return The value of the 'org_url' field.
   */
  public java.lang.CharSequence getOrgUrl() {
    return org_url;
  }

  /**
   * Sets the value of the 'org_url' field.
   * @param value the value to set.
   */
  public void setOrgUrl(java.lang.CharSequence value) {
    this.org_url = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.lang.Long getCreatedAt() {
    return created_at;
  }

  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.Long value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'other' field.
   * @return The value of the 'other' field.
   */
  public java.lang.CharSequence getOther() {
    return other;
  }

  /**
   * Sets the value of the 'other' field.
   * @param value the value to set.
   */
  public void setOther(java.lang.CharSequence value) {
    this.other = value;
  }

  /**
   * Gets the value of the 'rnd' field.
   * @return The value of the 'rnd' field.
   */
  public java.lang.Double getRnd() {
    return rnd;
  }

  /**
   * Sets the value of the 'rnd' field.
   * @param value the value to set.
   */
  public void setRnd(java.lang.Double value) {
    this.rnd = value;
  }

  /**
   * Creates a new Root RecordBuilder.
   * @return A new Root RecordBuilder
   */
  public static com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder newBuilder() {
    return new com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder();
  }

  /**
   * Creates a new Root RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Root RecordBuilder
   */
  public static com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder newBuilder(com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder other) {
    return new com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder(other);
  }

  /**
   * Creates a new Root RecordBuilder by copying an existing Root instance.
   * @param other The existing instance to copy.
   * @return A new Root RecordBuilder
   */
  public static com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder newBuilder(com.drfloob.insight.pulse.schema.gh.y2015.Root other) {
    return new com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder(other);
  }

  /**
   * RecordBuilder for Root instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Root>
    implements org.apache.avro.data.RecordBuilder<Root> {

    private java.lang.CharSequence type;
    private java.lang.Boolean public$;
    private java.lang.CharSequence payload;
    private java.lang.Long repo_id;
    private java.lang.CharSequence repo_name;
    private java.lang.CharSequence repo_url;
    private java.lang.Long actor_id;
    private java.lang.CharSequence actor_login;
    private java.lang.CharSequence actor_gravatar_id;
    private java.lang.CharSequence actor_avatar_url;
    private java.lang.CharSequence actor_url;
    private java.lang.Long org_id;
    private java.lang.CharSequence org_login;
    private java.lang.CharSequence org_gravatar_id;
    private java.lang.CharSequence org_avatar_url;
    private java.lang.CharSequence org_url;
    private java.lang.Long created_at;
    private java.lang.CharSequence id;
    private java.lang.CharSequence other;
    private java.lang.Double rnd;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.public$)) {
        this.public$ = data().deepCopy(fields()[1].schema(), other.public$);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.payload)) {
        this.payload = data().deepCopy(fields()[2].schema(), other.payload);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.repo_id)) {
        this.repo_id = data().deepCopy(fields()[3].schema(), other.repo_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.repo_name)) {
        this.repo_name = data().deepCopy(fields()[4].schema(), other.repo_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.repo_url)) {
        this.repo_url = data().deepCopy(fields()[5].schema(), other.repo_url);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.actor_id)) {
        this.actor_id = data().deepCopy(fields()[6].schema(), other.actor_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.actor_login)) {
        this.actor_login = data().deepCopy(fields()[7].schema(), other.actor_login);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.actor_gravatar_id)) {
        this.actor_gravatar_id = data().deepCopy(fields()[8].schema(), other.actor_gravatar_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.actor_avatar_url)) {
        this.actor_avatar_url = data().deepCopy(fields()[9].schema(), other.actor_avatar_url);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.actor_url)) {
        this.actor_url = data().deepCopy(fields()[10].schema(), other.actor_url);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.org_id)) {
        this.org_id = data().deepCopy(fields()[11].schema(), other.org_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.org_login)) {
        this.org_login = data().deepCopy(fields()[12].schema(), other.org_login);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.org_gravatar_id)) {
        this.org_gravatar_id = data().deepCopy(fields()[13].schema(), other.org_gravatar_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.org_avatar_url)) {
        this.org_avatar_url = data().deepCopy(fields()[14].schema(), other.org_avatar_url);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.org_url)) {
        this.org_url = data().deepCopy(fields()[15].schema(), other.org_url);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.created_at)) {
        this.created_at = data().deepCopy(fields()[16].schema(), other.created_at);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.id)) {
        this.id = data().deepCopy(fields()[17].schema(), other.id);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.other)) {
        this.other = data().deepCopy(fields()[18].schema(), other.other);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.rnd)) {
        this.rnd = data().deepCopy(fields()[19].schema(), other.rnd);
        fieldSetFlags()[19] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Root instance
     * @param other The existing instance to copy.
     */
    private Builder(com.drfloob.insight.pulse.schema.gh.y2015.Root other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.public$)) {
        this.public$ = data().deepCopy(fields()[1].schema(), other.public$);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.payload)) {
        this.payload = data().deepCopy(fields()[2].schema(), other.payload);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.repo_id)) {
        this.repo_id = data().deepCopy(fields()[3].schema(), other.repo_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.repo_name)) {
        this.repo_name = data().deepCopy(fields()[4].schema(), other.repo_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.repo_url)) {
        this.repo_url = data().deepCopy(fields()[5].schema(), other.repo_url);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.actor_id)) {
        this.actor_id = data().deepCopy(fields()[6].schema(), other.actor_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.actor_login)) {
        this.actor_login = data().deepCopy(fields()[7].schema(), other.actor_login);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.actor_gravatar_id)) {
        this.actor_gravatar_id = data().deepCopy(fields()[8].schema(), other.actor_gravatar_id);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.actor_avatar_url)) {
        this.actor_avatar_url = data().deepCopy(fields()[9].schema(), other.actor_avatar_url);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.actor_url)) {
        this.actor_url = data().deepCopy(fields()[10].schema(), other.actor_url);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.org_id)) {
        this.org_id = data().deepCopy(fields()[11].schema(), other.org_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.org_login)) {
        this.org_login = data().deepCopy(fields()[12].schema(), other.org_login);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.org_gravatar_id)) {
        this.org_gravatar_id = data().deepCopy(fields()[13].schema(), other.org_gravatar_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.org_avatar_url)) {
        this.org_avatar_url = data().deepCopy(fields()[14].schema(), other.org_avatar_url);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.org_url)) {
        this.org_url = data().deepCopy(fields()[15].schema(), other.org_url);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.created_at)) {
        this.created_at = data().deepCopy(fields()[16].schema(), other.created_at);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.id)) {
        this.id = data().deepCopy(fields()[17].schema(), other.id);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.other)) {
        this.other = data().deepCopy(fields()[18].schema(), other.other);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.rnd)) {
        this.rnd = data().deepCopy(fields()[19].schema(), other.rnd);
        fieldSetFlags()[19] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'public$' field.
      * @return The value.
      */
    public java.lang.Boolean getPublic$() {
      return public$;
    }

    /**
      * Sets the value of the 'public$' field.
      * @param value The value of 'public$'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setPublic$(java.lang.Boolean value) {
      validate(fields()[1], value);
      this.public$ = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'public$' field has been set.
      * @return True if the 'public$' field has been set, false otherwise.
      */
    public boolean hasPublic$() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'public$' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearPublic$() {
      public$ = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'payload' field.
      * @return The value.
      */
    public java.lang.CharSequence getPayload() {
      return payload;
    }

    /**
      * Sets the value of the 'payload' field.
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setPayload(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.payload = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'payload' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'repo_id' field.
      * @return The value.
      */
    public java.lang.Long getRepoId() {
      return repo_id;
    }

    /**
      * Sets the value of the 'repo_id' field.
      * @param value The value of 'repo_id'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setRepoId(java.lang.Long value) {
      validate(fields()[3], value);
      this.repo_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'repo_id' field has been set.
      * @return True if the 'repo_id' field has been set, false otherwise.
      */
    public boolean hasRepoId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'repo_id' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearRepoId() {
      repo_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'repo_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getRepoName() {
      return repo_name;
    }

    /**
      * Sets the value of the 'repo_name' field.
      * @param value The value of 'repo_name'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setRepoName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.repo_name = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'repo_name' field has been set.
      * @return True if the 'repo_name' field has been set, false otherwise.
      */
    public boolean hasRepoName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'repo_name' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearRepoName() {
      repo_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'repo_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getRepoUrl() {
      return repo_url;
    }

    /**
      * Sets the value of the 'repo_url' field.
      * @param value The value of 'repo_url'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setRepoUrl(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.repo_url = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'repo_url' field has been set.
      * @return True if the 'repo_url' field has been set, false otherwise.
      */
    public boolean hasRepoUrl() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'repo_url' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearRepoUrl() {
      repo_url = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'actor_id' field.
      * @return The value.
      */
    public java.lang.Long getActorId() {
      return actor_id;
    }

    /**
      * Sets the value of the 'actor_id' field.
      * @param value The value of 'actor_id'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setActorId(java.lang.Long value) {
      validate(fields()[6], value);
      this.actor_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'actor_id' field has been set.
      * @return True if the 'actor_id' field has been set, false otherwise.
      */
    public boolean hasActorId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'actor_id' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearActorId() {
      actor_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'actor_login' field.
      * @return The value.
      */
    public java.lang.CharSequence getActorLogin() {
      return actor_login;
    }

    /**
      * Sets the value of the 'actor_login' field.
      * @param value The value of 'actor_login'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setActorLogin(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.actor_login = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'actor_login' field has been set.
      * @return True if the 'actor_login' field has been set, false otherwise.
      */
    public boolean hasActorLogin() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'actor_login' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearActorLogin() {
      actor_login = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'actor_gravatar_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getActorGravatarId() {
      return actor_gravatar_id;
    }

    /**
      * Sets the value of the 'actor_gravatar_id' field.
      * @param value The value of 'actor_gravatar_id'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setActorGravatarId(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.actor_gravatar_id = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'actor_gravatar_id' field has been set.
      * @return True if the 'actor_gravatar_id' field has been set, false otherwise.
      */
    public boolean hasActorGravatarId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'actor_gravatar_id' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearActorGravatarId() {
      actor_gravatar_id = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'actor_avatar_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getActorAvatarUrl() {
      return actor_avatar_url;
    }

    /**
      * Sets the value of the 'actor_avatar_url' field.
      * @param value The value of 'actor_avatar_url'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setActorAvatarUrl(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.actor_avatar_url = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'actor_avatar_url' field has been set.
      * @return True if the 'actor_avatar_url' field has been set, false otherwise.
      */
    public boolean hasActorAvatarUrl() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'actor_avatar_url' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearActorAvatarUrl() {
      actor_avatar_url = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'actor_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getActorUrl() {
      return actor_url;
    }

    /**
      * Sets the value of the 'actor_url' field.
      * @param value The value of 'actor_url'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setActorUrl(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.actor_url = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'actor_url' field has been set.
      * @return True if the 'actor_url' field has been set, false otherwise.
      */
    public boolean hasActorUrl() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'actor_url' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearActorUrl() {
      actor_url = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_id' field.
      * @return The value.
      */
    public java.lang.Long getOrgId() {
      return org_id;
    }

    /**
      * Sets the value of the 'org_id' field.
      * @param value The value of 'org_id'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setOrgId(java.lang.Long value) {
      validate(fields()[11], value);
      this.org_id = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'org_id' field has been set.
      * @return True if the 'org_id' field has been set, false otherwise.
      */
    public boolean hasOrgId() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'org_id' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearOrgId() {
      org_id = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_login' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrgLogin() {
      return org_login;
    }

    /**
      * Sets the value of the 'org_login' field.
      * @param value The value of 'org_login'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setOrgLogin(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.org_login = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'org_login' field has been set.
      * @return True if the 'org_login' field has been set, false otherwise.
      */
    public boolean hasOrgLogin() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'org_login' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearOrgLogin() {
      org_login = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_gravatar_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrgGravatarId() {
      return org_gravatar_id;
    }

    /**
      * Sets the value of the 'org_gravatar_id' field.
      * @param value The value of 'org_gravatar_id'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setOrgGravatarId(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.org_gravatar_id = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'org_gravatar_id' field has been set.
      * @return True if the 'org_gravatar_id' field has been set, false otherwise.
      */
    public boolean hasOrgGravatarId() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'org_gravatar_id' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearOrgGravatarId() {
      org_gravatar_id = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_avatar_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrgAvatarUrl() {
      return org_avatar_url;
    }

    /**
      * Sets the value of the 'org_avatar_url' field.
      * @param value The value of 'org_avatar_url'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setOrgAvatarUrl(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.org_avatar_url = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'org_avatar_url' field has been set.
      * @return True if the 'org_avatar_url' field has been set, false otherwise.
      */
    public boolean hasOrgAvatarUrl() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'org_avatar_url' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearOrgAvatarUrl() {
      org_avatar_url = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'org_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrgUrl() {
      return org_url;
    }

    /**
      * Sets the value of the 'org_url' field.
      * @param value The value of 'org_url'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setOrgUrl(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.org_url = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'org_url' field has been set.
      * @return True if the 'org_url' field has been set, false otherwise.
      */
    public boolean hasOrgUrl() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'org_url' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearOrgUrl() {
      org_url = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.lang.Long getCreatedAt() {
      return created_at;
    }

    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setCreatedAt(java.lang.Long value) {
      validate(fields()[16], value);
      this.created_at = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setId(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.id = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearId() {
      id = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'other' field.
      * @return The value.
      */
    public java.lang.CharSequence getOther() {
      return other;
    }

    /**
      * Sets the value of the 'other' field.
      * @param value The value of 'other'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setOther(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.other = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'other' field has been set.
      * @return True if the 'other' field has been set, false otherwise.
      */
    public boolean hasOther() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'other' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearOther() {
      other = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'rnd' field.
      * @return The value.
      */
    public java.lang.Double getRnd() {
      return rnd;
    }

    /**
      * Sets the value of the 'rnd' field.
      * @param value The value of 'rnd'.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder setRnd(java.lang.Double value) {
      validate(fields()[19], value);
      this.rnd = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'rnd' field has been set.
      * @return True if the 'rnd' field has been set, false otherwise.
      */
    public boolean hasRnd() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'rnd' field.
      * @return This builder.
      */
    public com.drfloob.insight.pulse.schema.gh.y2015.Root.Builder clearRnd() {
      rnd = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    public Root build() {
      try {
        Root record = new Root();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.public$ = fieldSetFlags()[1] ? this.public$ : (java.lang.Boolean) defaultValue(fields()[1]);
        record.payload = fieldSetFlags()[2] ? this.payload : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.repo_id = fieldSetFlags()[3] ? this.repo_id : (java.lang.Long) defaultValue(fields()[3]);
        record.repo_name = fieldSetFlags()[4] ? this.repo_name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.repo_url = fieldSetFlags()[5] ? this.repo_url : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.actor_id = fieldSetFlags()[6] ? this.actor_id : (java.lang.Long) defaultValue(fields()[6]);
        record.actor_login = fieldSetFlags()[7] ? this.actor_login : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.actor_gravatar_id = fieldSetFlags()[8] ? this.actor_gravatar_id : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.actor_avatar_url = fieldSetFlags()[9] ? this.actor_avatar_url : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.actor_url = fieldSetFlags()[10] ? this.actor_url : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.org_id = fieldSetFlags()[11] ? this.org_id : (java.lang.Long) defaultValue(fields()[11]);
        record.org_login = fieldSetFlags()[12] ? this.org_login : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.org_gravatar_id = fieldSetFlags()[13] ? this.org_gravatar_id : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.org_avatar_url = fieldSetFlags()[14] ? this.org_avatar_url : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.org_url = fieldSetFlags()[15] ? this.org_url : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.created_at = fieldSetFlags()[16] ? this.created_at : (java.lang.Long) defaultValue(fields()[16]);
        record.id = fieldSetFlags()[17] ? this.id : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.other = fieldSetFlags()[18] ? this.other : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.rnd = fieldSetFlags()[19] ? this.rnd : (java.lang.Double) defaultValue(fields()[19]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
